language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgtest-dev valgrind

script: ./build.sh
